---
name: Lint Code Base

concurrency:
  group: rust-linter-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Lint Code Base
        id: linter
        run: nix develop -c cargo clippy
